### ISSUE TITLE
Submit to WordPress directory checklist

### ISSUE THREAD

**Issue by CodyReichert** [identibyte/identibyte-for-contact-form-7#1]
Only a couple of things needed before we can submit to the WordPress directory:

- [x] Add link to GPLv3 license file
- [x] Add readme.txt
- [x] Go through WordPress Developer Checklist
- [x] Add screenshots
- [x] Submit to WordPress Directory

**Follow-up**
- [ ] Add banner image for WP page

---

### (Feedback Loop 1](https://github.com/identibyte/cf7-identibyte/issues/1#issuecomment-450414427)
> First set of feedback tasks from the WordPress team

- [x] Sanitize inputs (9c5d6557ab57b228ffa6aaf30b19246e2b3e7a8b)
- [x] Check in logo image (a38f40c41ca786c018ea9b92669dabdd78a624c2)
- [x] Update readme abt 3rd party service  (65d1545d71d3bf4c216b36dd51680e53fc2a775d)
- [ ] Send new `.zip` file to WordPress team

**Comment by CodyReichert** [comment]
Alright we got some feedback with just a couple of things to fix and clarify in the readme.txt. Paraphrased here:

---

## Please sanitize, escape, and validate your POST calls 

When you include POST/GET/REQUEST/FILE calls in your plugin, it's important to sanitize, validate, and escape them. The goal here is to prevent a user from accidentally sending trash data through the system, as well as protecting them from potential security issues. Some examples from your plugin:

```php
        $value_ = $_POST[$tag->name];
        $value = trim($value_);
```

In function cf7_identibyte_make_check that gets set here:

```php
$url = "https://identibyte.com/check/" . $data . $api_token;
```

At the very lease you should slap an esc_url() around that.

## Calling images remotely 

Offloading images to your own server is disallowed.  Please include all images needed for your plugin locally. 

Example: src="https://identibyte.com/static/img/logo-120x120.png"

## Undocumented use of a 3rd Party or external service

You call https://identibyte.com

While this is actually okay, you neglected to fully document this in your readme. You must update your readme to do the following:

* clearly explain that your plugin is relying on a 3rd party as a service and under what circumstances
* provide a link to the service
* provide a link to the services’ a terms of use and/or privacy policies
